spring.application.name=game-log-backend

# DB in Container
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.hibernate=INFO


# Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging for developping stage
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

